#!/bin/bash

# Validate $1 is i3 or sway
if [ "$1" != "i3" ] && [ "$1" != "sway" ]; then
    echo "Invalid window manager"
    exit 1
fi

./scripts/configure.sh
./scripts/fonts.sh
./scripts/software.sh

if [ "$1" == "i3" ]; then
    ./scripts/xorg.sh
    ./scripts/i3.sh
elif [ "$1" == "sway" ]; then
    ./scripts/sway.sh
else
    echo "No window manager selected"
fi

./scripts/polybar.sh
./scripts/zsh.sh $1
./scripts/development.sh
./scripts/systemd.sh
./scripts/autostart.sh

# Create some folders
mkdir -p $HOME/bin
mkdir -p $HOME/BingWallpaper
mkdir -p $HOME/captures

# Create captures dir
mkdir -p $HOME/captures

# Configure terminator
mkdir -p $HOME/.config/terminator
ln -sv $HOME/dotfiles/config/terminator/config $HOME/.config/terminator/config

# Add scripts
ln -sv $HOME/dotfiles/bin/get-wallpaper.sh $HOME/bin/get-wallpaper
ln -sv $HOME/dotfiles/bin/images-versions $HOME/bin/images-versions
ln -sv $HOME/dotfiles/bin/switch-keyboard $HOME/bin/switch-keyboard
ln -sv $HOME/dotfiles/bin/git-hist $HOME/bin/git-hist
ln -sv $HOME/dotfiles/bin/lock $HOME/bin/lock
