general {
    hide_cursor = true
    grace = 3
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgb(8aadf4)
    inner_color = rgb(24273a)
    font_color = rgb(cad3f5)
    fade_on_empty = true
    placeholder_text = <span foreground="##a5adcb">Password...</span>
    hide_input = false
    rounding = 10
    check_color = rgb(a6da95)
    fail_color = rgb(ed8796)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(cad3f5)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    color = rgb(b7bdf8)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
