fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh


ZSH_CUSTOM=$HOME/.zsh_custom
ZSH_THEME="spaceship"
# SPACESHIP_KUBECTL_SHOW=true
# SPACESHIP_TIME_SHOW=true

plugins=(
  git
  git-extras
  sudo
  docker
  yarn
  npm
  web-search
  zsh-autosuggestions
  zsh-wakatime
  kubectl
  zsh-kubectl-prompt
)

DEFAULT_USER=pedroapy
