color_theme = "catppuccin_macchiato"
theme_background = False
truecolor = True
rounded_corners = True
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_tree = False
proc_per_core = False
cpu_single_graph = False
show_gpu_info = "Auto"
